// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }



// import type { Metadata } from "next";
// import { AuthProvider } from "./components/AuthContext";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Agri Bot",
//   description: "Agricultural monitoring and threat detection system",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <head>
//         {/* 
//           This script runs BEFORE React hydrates — prevents white flash 
//           on page load when user has dark mode saved.
//           suppressHydrationWarning on <html> is required for this pattern.
//         */}
//         <script
//           dangerouslySetInnerHTML={{
//             __html: `
//               try {
//                 var t = localStorage.getItem('theme');
//                 if (t === 'dark' || (!t && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
//                   document.documentElement.classList.add('dark');
//                 }
//               } catch(e) {}
//             `,
//           }}
//         />
//       </head>
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//         <AuthProvider>
//           {children}
//         </AuthProvider>
//       </body>
//     </html>
//   );
// }


// import type { Metadata } from "next";
// import { AuthProvider } from "./components/AuthContext";
// import Providers from "./components/Providers";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Agri Bot",
//   description: "Agricultural monitoring and threat detection system",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <head>
//         {/* 
//           This script runs BEFORE React hydrates — prevents white flash 
//           on page load when user has dark mode saved.
//           suppressHydrationWarning on <html> is required for this pattern.
//         */}
//         <script
//           dangerouslySetInnerHTML={{
//             __html: `
//               try {
//                 var t = localStorage.getItem('theme');
//                 if (t === 'dark' || (!t && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
//                   document.documentElement.classList.add('dark');
//                 }
//               } catch(e) {}
//             `,
//           }}
//         />
//       </head>
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//         <Providers>
//           <AuthProvider>
//             {children}
//           </AuthProvider>
//         </Providers>
//       </body>
//     </html>
//   );
// }


// import type { Metadata } from "next";
// import { AuthProvider } from "./components/AuthContext";
// import Providers from "./components/Providers";
// import FullscreenToggle from "./components/FullscreenToggle";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Agri Bot",
//   description: "Agricultural monitoring and threat detection system",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <head>
//         {/*
//           This script runs BEFORE React hydrates — prevents white flash
//           on page load when user has dark mode saved.
//           suppressHydrationWarning on <html> is required for this pattern.
//         */}
//         <script
//           dangerouslySetInnerHTML={{
//             __html: `
//               try {
//                 var t = localStorage.getItem('theme');
//                 if (t === 'dark' || (!t && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
//                   document.documentElement.classList.add('dark');
//                 }
//               } catch(e) {}
//             `,
//           }}
//         />
//       </head>
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//         <Providers>
//           <AuthProvider>
//             <FullscreenToggle />  {/* Global — appears on every page */}
//             {children}
//           </AuthProvider>
//         </Providers>
//       </body>
//     </html>
//   );
// }



import type { Metadata } from "next";
import { AuthProvider } from "./components/AuthContext";
import Providers from "./components/Providers";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Agri Bot",
  description: "Agricultural monitoring and threat detection system",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/*
          This script runs BEFORE React hydrates — prevents white flash
          on page load when user has dark mode saved.
          suppressHydrationWarning on <html> is required for this pattern.
        */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              try {
                var t = localStorage.getItem('theme');
                if (t === 'dark' || (!t && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
                  document.documentElement.classList.add('dark');
                }
              } catch(e) {}
            `,
          }}
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <AuthProvider>
            {children}
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}